// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineCourseManagement.Models;

#nullable disable

namespace OnlineCourseManagement.Migrations
{
    [DbContext(typeof(OnlineCourseManagementDbContext))]
    [Migration("20260322190903_InitialWithEnums")]
    partial class InitialWithEnums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineCourseManagement.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Courses__3214EC079C42C126");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Lectures__3214EC0749266654");

                    b.HasIndex(new[] { "CourseId" }, "IX_Lectures_CourseId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.LectureVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LectureId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK__LectureV__3214EC0765EDDA64");

                    b.HasIndex(new[] { "LectureId" }, "IX_LectureVideos_LectureId");

                    b.ToTable("LectureVideos");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.LecturersCourse", b =>
                {
                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LecturerId", "CourseId")
                        .HasName("PK__Lecturer__36EA6E27A308D3F4");

                    b.HasIndex("CourseId");

                    b.ToTable("LecturersCourses");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC077FD34294");

                    b.HasIndex("PurchaseId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Purchase__3214EC0757BF6E1A");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "UserId", "CourseId" }, "UX_Purchases_User_Course")
                        .IsUnique();

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.StudentsCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("EnrolledAT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Grade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("StudentId", "CourseId")
                        .HasName("PK__Students__5E57FC837298EC71");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentsCourses");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfileImageContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImageFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC079E27A083");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Lecture", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Course", "Course")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Course_Lecture");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.LectureVideo", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Lecture", "Lecture")
                        .WithMany("LectureVideos")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Lecture_LectureVideos");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.LecturersCourse", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Course", "Course")
                        .WithMany("LecturersCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Lecturers__Cours__0A9D95DB");

                    b.HasOne("OnlineCourseManagement.Models.User", "Lecturer")
                        .WithMany("LecturersCourses")
                        .HasForeignKey("LecturerId")
                        .IsRequired()
                        .HasConstraintName("FK__Lecturers__Lectu__09A971A2");

                    b.Navigation("Course");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Payment", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Purchase", "Purchase")
                        .WithMany("Payments")
                        .HasForeignKey("PurchaseId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Purchases");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Purchase", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Course", "Course")
                        .WithMany("Purchases")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Purchases_Courses");

                    b.HasOne("OnlineCourseManagement.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Purchases_Users");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.StudentsCourse", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Course", "Course")
                        .WithMany("StudentsCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentsC__Cours__06CD04F7");

                    b.HasOne("OnlineCourseManagement.Models.User", "Student")
                        .WithMany("StudentsCourses")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentsC__Stude__05D8E0BE");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Course", b =>
                {
                    b.Navigation("LecturersCourses");

                    b.Navigation("Lectures");

                    b.Navigation("Purchases");

                    b.Navigation("StudentsCourses");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Lecture", b =>
                {
                    b.Navigation("LectureVideos");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Purchase", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.User", b =>
                {
                    b.Navigation("LecturersCourses");

                    b.Navigation("Purchases");

                    b.Navigation("StudentsCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
