// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineCourseManagement.Models;

#nullable disable

namespace OnlineCourseManagement.Migrations
{
    [DbContext(typeof(OnlineCourseManagementDbContext))]
    partial class OnlineCourseManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineCourseManagement.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Courses__3214EC079C42C126");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Lectures__3214EC0749266654");

                    b.HasIndex(new[] { "CourseId" }, "IX_Lectures_CourseId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.LectureVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LectureId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK__LectureV__3214EC0765EDDA64");

                    b.HasIndex(new[] { "LectureId" }, "IX_LectureVideos_LectureId");

                    b.ToTable("LectureVideos");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.LecturersCourse", b =>
                {
                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LecturerId", "CourseId")
                        .HasName("PK__Lecturer__36EA6E27A308D3F4");

                    b.HasIndex(new[] { "CourseId" }, "IX_LecturersCourses_CourseId");

                    b.ToTable("LecturersCourses");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Position__3214EC07D9D8112D");

                    b.ToTable("Position", (string)null);
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.PurchaseCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Purchase__3214EC07CA029FCE");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.StudentsCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("EnrolledAT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Grade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId")
                        .HasName("PK__Students__5E57FC837298EC71");

                    b.HasIndex(new[] { "CourseId" }, "IX_StudentsCourses_CourseId");

                    b.ToTable("StudentsCourses");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfileImageContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImageFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC079E27A083");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.UsersPosition", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.HasKey("UsersId", "PositionId")
                        .HasName("PK__UsersPos__254209C504877765");

                    b.HasIndex(new[] { "PositionId" }, "IX_UsersPosition_PositionId");

                    b.ToTable("UsersPosition", (string)null);
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Lecture", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Course", "Course")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Course_Lecture");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.LectureVideo", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Lecture", "Lecture")
                        .WithMany("LectureVideos")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Lecture_LectureVideos");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.LecturersCourse", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Course", "Course")
                        .WithMany("LecturersCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Lecturers__Cours__0A9D95DB");

                    b.HasOne("OnlineCourseManagement.Models.User", "Lecturer")
                        .WithMany("LecturersCourses")
                        .HasForeignKey("LecturerId")
                        .IsRequired()
                        .HasConstraintName("FK__Lecturers__Lectu__09A971A2");

                    b.Navigation("Course");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.PurchaseCourse", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Course", "Course")
                        .WithMany("Purchases")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Purchases__Cours__17F790F9");

                    b.HasOne("OnlineCourseManagement.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Purchases__UserI__17036CC0");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.StudentsCourse", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Course", "Course")
                        .WithMany("StudentsCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentsC__Cours__06CD04F7");

                    b.HasOne("OnlineCourseManagement.Models.User", "Student")
                        .WithMany("StudentsCourses")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentsC__Stude__05D8E0BE");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.UsersPosition", b =>
                {
                    b.HasOne("OnlineCourseManagement.Models.Position", "Position")
                        .WithMany("UsersPositions")
                        .HasForeignKey("PositionId")
                        .IsRequired()
                        .HasConstraintName("FK__UsersPosi__Posit__797309D9");

                    b.HasOne("OnlineCourseManagement.Models.User", "Users")
                        .WithMany("UsersPositions")
                        .HasForeignKey("UsersId")
                        .IsRequired()
                        .HasConstraintName("FK__UsersPosi__Users__787EE5A0");

                    b.Navigation("Position");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Course", b =>
                {
                    b.Navigation("LecturersCourses");

                    b.Navigation("Lectures");

                    b.Navigation("Purchases");

                    b.Navigation("StudentsCourses");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Lecture", b =>
                {
                    b.Navigation("LectureVideos");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.Position", b =>
                {
                    b.Navigation("UsersPositions");
                });

            modelBuilder.Entity("OnlineCourseManagement.Models.User", b =>
                {
                    b.Navigation("LecturersCourses");

                    b.Navigation("Purchases");

                    b.Navigation("StudentsCourses");

                    b.Navigation("UsersPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
